user:
  #username 学号或者工号
  username: '5820219221'
  #address 地址，定位信息
  address: 中国江西省鹰潭市贵溪市信江北大道58号
  #email 接受通知消息的邮箱
  email: 2512631900@qq.com
  #school 学校全称
  school: 江西理工大学
  #lon 经度
  lon: '117.043134'
  #lat 纬度
  lat: '28.301218'
  #abnormalReason 不在范围的原因
  abnormalReason:
  #photo 签到照片，不需要可不填，或者直接删除
  photo: pe.jpeg
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理
    - default:
      #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片
